# Generated by Django 5.2a1 on 2025-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_examregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.TextField()),
            ],
            options={
                "db_table": "subjects",
            },
        ),
        migrations.RenameField(
            model_name="room",
            old_name="rum_number",
            new_name="room_number",
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
    ]
