# Generated by Django 5.2a1 on 2025-02-13 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="room_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.room",
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examregistration",
            unique_together={("exam", "user")},
        ),
    ]
