# Generated by Django 5.2a1 on 2025-02-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_exam_room_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="room_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.room"
            ),
        ),
    ]
