# Generated by Django 5.2a1 on 2025-02-17 08:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_organization", "0003_teacher_subjectunit_exam"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(null=True, unique=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("лекторий", "Lecture Hall"),
                            ("лаборатория", "Laboratory"),
                            ("обычный", "Common"),
                            ("онлайн", "Online"),
                        ]
                    ),
                ),
                ("number_of_seats", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="date_time",
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="format",
            field=models.TextField(
                choices=[("письменный", "Written"), ("устный", "Oral")],
                default=datetime.datetime(2025, 2, 17, 11, 3, 25, 226513),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="responsible_teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_organization.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="related_exam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exam_organization.exam",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="patronymic",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_organization.room",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forename", models.TextField()),
                ("surname", models.TextField()),
                ("patronymic", models.TextField(null=True)),
                ("passport_number", models.IntegerField(unique=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_organization.group",
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
