name: "Lint and test"

on:
    push:
    pull_request:

jobs:
    lint_and_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Flake8
              run: uv run black --check --diff --verbose smart_time_test

            - name: Black
              run: uv run flake8 --toml-config pyproject.toml --verbose smart_time_test

            - name: Test
              run: cd smart_time_test && uv run manage.py test
